### ISSUE TITLE
[ Enhancement Suggestion ] Cryptocurrency used for donation

### ISSUE THREAD

**Issue by keitenai** [rathena/FluxCP#161]
Hello!
It would be nice if we can implement cryptocurrency as donation option.

**Comment by Akkarinage** [comment]
There was a plan a few years back to implement additional payment platforms but nothing happened with it. Cryptocurrency was ruled out due to the unregulated nature of global person-to-person economy.

Developers also considered payment platforms such as Stripe and WorldPay integrations, but again, nothing came of it. Because Paypal is capable of accepting debit/credit cards, bank funding and account credit we left it as the only payment module. If anyone has suggestions for specific platforms (and detailing pros and cons) i'm willing to look into it.

**Comment by SneakyRO** [comment]
Stripe is great, it's more a direct appeal. Paypal also can accept cards but it's overshadowed because they obviously want people to sign up.

Also would love to see cryptocurrency support somehow!

**Comment by Akkarinage** [comment]
I won't get involved with Cryptocurrency, but Stripe is an option.

**Comment by xlChaoslx** [comment]
Cryptocurrency, I'd vote up on that.

**Comment by Akkarinage** [comment]
I'm going to close this off as I have no intention of adding cryptocurrency to FluxCP. IF anyone wants to create a PR to add this feature they're welcome to do so.
