### ISSUE TITLE
Just a suggestions

### ISSUE THREAD

**Issue by ghost** [rathena/FluxCP#163]
Adding an option to toggle wherein fees for paypal will be included or not.

**Comment by Akkarinage** [comment]
Paypal sets their transaction fees as a percentage + flat rate fee depending on the countries the sending and receiving account is registered in, and in some countries the percentage and/or flat rate fee is dependant upon the type of transaction (donation/service/goods/etc).

Unsure why you'd ned to worry about adding the fees on top of the transaction - it's not like you're loosing money since it's not a physical product that you're shipping.
