### ISSUE TITLE
Item Database not working anymore

### ISSUE THREAD

**Issue by bgamez23** [rathena/FluxCP#270]
for the latest version of rathena. item database is no longer working. you can't view any item but on monster database it will show the monsters but it has no drops

**Comment by Balferian** [comment]
@bgamez23 I`m working on update.
For now you can use this tool:
https://github.com/rathena/rathena/tree/master/sql-files/compatibility

**Comment by bgamez23** [comment]
oh okay thanks.

**Comment by pauljohntinoco** [comment]
@bgamez23 i import those sql files to my ragnarok database . but still not working ehen viewing item db on fluxcp. Thanks

**Comment by Ninjininja** [comment]
> @bgamez23 i import those sql files to my ragnarok database . but still not working ehen viewing item db on fluxcp. Thanks

You have to go into **modules\item** and look for the file called **iteminfo.php**

Once in there you gotta change which database it's looking at, to the new "compat" views. So in my case, because I'm Renewal, I went to the following:

    **if($server->isRenewal) {
        $fromTables = array("{$server->charMapDatabase}.item_db_re", "{$server->charMapDatabase}.item_db2_re");
    } else {
        $fromTables = array("{$server->charMapDatabase}.item_db", "{$server->charMapDatabase}.item_db2");
    }**


And then I altered that entry to read the following and it worked again:


    **if($server->isRenewal) {
        $fromTables = array("{$server->charMapDatabase}.item_db_re_compat", "{$server->charMapDatabase}.item_db2_re_compat");
    } else {
        $fromTables = array("{$server->charMapDatabase}.item_db", "{$server->charMapDatabase}.item_db2");
    }**

**Comment by basteerulezz** [comment]
I have tried to use the compat sql files, and i checked on my sql database there's _compat database there under the view, and i already edit index.php on item folder, but fluxcp still unable to show my item and mob db
Is anyone still have the old (before the changes I presume on oct 2020?) item_db_re.sql and item_db2_re.sql files?

**Comment by Balferian** [comment]
> I have tried to use the compat sql files, and i checked on my sql database there's _compat database there under the view, and i already edit index.php on item folder, but fluxcp still unable to show my item and mob db
> Is anyone still have the old (before the changes I presume on oct 2020?) item_db_re.sql and item_db2_re.sql files?
> 
> Edit : Found it, im asking on discord, and got the help to find it
> 
> [Fix FluxCP Itemdb and mobdb.zip](https://github.com/rathena/FluxCP/files/6138116/Fix.FluxCP.Itemdb.and.mobdb.zip)
> (edited : more complete files)
> For those that fluxcp still not working, here's the sql alternate to the old version, its working for me, don't forget to change the module\item\index.php files as mentioned by Ninjininja above

@bgamez23 It's just old sql tables and an old modules.
They will not display up-to-date information from the server.
Can you enable debug mode and show me errors?

**Comment by hendra814** [comment]
@Ninjininja and @basteerulezz,

That's setting only for database, if go to my account still got error.

**Comment by Lemongrass3110** [comment]
Fixed in d83a7f6
