### ISSUE TITLE
Built-In Forums Module

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#67]
How do you guys feel about this? Would you prefer something built-in with features that tie into the player's account/chars to keep things nice and tidy? I know there was a guide once on how to integrate fluxbb (not related to fluxcp) to use it as a module, but it's not been updated in 6 months and is coated in bugs.

I'd started writing a forum module about 2 years ago when I first uploaded akkarinage/fluxcp before it went over to rAthena, so it won't take alot of work for basic topic/post/category functions to be finished.

But like I said, how do you guys feel about this?

**Comment by Mysteries** [comment]
Hm... maybe use IPB's rest API to intertwine accounts? Or other forum software APIs? Also, if you're going to be making a built in forum, I assume its going to be minimalistic ?

**Comment by Akkarinage** [comment]
If we used APIs then there'd be no point in adding a built-in option :stuck_out_tongue: Almost all popular forum software has the ability to use the `login` table to fetch account data instead of standalone registrations. This idea is to provide the option to eliminate the need for additional software.

The version i'm already testing is minimalist, but I'm slowly adding features for alternative theme/layouts, IPB's multimod function, etc etc. It's by no means a simple module.

**Comment by aleos89** [comment]
Sounds like the StarXCP? Where it had the small forum application built into the CP. It is a cool feature as it makes one less thing for players to make accounts with, and helps admins with association of accounts (security wise).

I would say if you have this feature primarily complete and also to where future updates would be easy enough then it would be nice to include. In all, it would be hard to compete with IPB and all the addons it supports.

**Comment by Mysteries** [comment]
Well I guess if you have a small server, having the forums built in wouldn't be that bad. Installing a forum would be one less thing a server owner would have to do.

**Comment by RagnarokNova** [comment]
What aleos said. I feel that it could potentially be a lot of work with not very much return, in the sense that there are entire forum softwares that receive so much more love and attention. Some premium such as IPS, and some free such as SMF.

**Comment by Vennren** [comment]
Having this feature would make it friendlier as a complete package. Even though eventually most people are using their own preferred forum software at some point for the additional features those provide.

It would be nice to include if it'll require low maintenance for it to keep working/adding small things. It shouldn't get the focus of the control panel system itself.

**Comment by anacondaqq** [comment]
Guys, you can't even fix super mega critical exploits in source code which is opened for years and you are totally ignore mine and other guys reports about them, and don't even reading PM messages about exploits which give access for hackers and steal db / do everything what they want at webhost.

About which "forum-software" are you talking about, if you can't even fix already reported information about very big security holes (which as i know not yet fixed) in fluxcp? Or are you want to create more security issues with flux?

**Comment by Akkarinage** [comment]
@anacondaqq feel free to send me a pm listing known exploits, i'd be happy to have a stab at fixing them.

**Comment by mrlongshen** [comment]
@akkarinage any updates about the build in forum?

**Comment by anacondaqq** [comment]
@mrlongshen 
Hi, sorry, this is maybe not correct from my side. But I must say about it because I think it's important.
Right now fluxcp very complicated and bogged control panel, adding extra modules which require a lot of power can't be done by only 1 guy or a small team of guys. I'm strongly against any extra modules in current fluxcp because it will totally kill any security in fluxcp. 

If are you asking it because you are looking for forum software, I can suggest checking few FREE and really nice forum software like:

- https://nodebb.org/
Example: https://forum.vivaldi.net/, https://notepad-plus-plus.org/community this forum software free, mega fast, very lightweight, has very big and mega powerful community around, tons of plugins, themes which developed by a very big team. Here is their official repo: https://github.com/NodeBB/NodeBB

- http://flarum.org/
example: https://discuss.flarum.org/ not so powerful workflow and team with too much progress, but still usable forum software. Very nice and features rich.

Why do I suggest it to you? 
Main idea: leave fluxcp as is without extra mega big modules, give dev's a chance to get from somewhere power and make fluxcp production ready and upgrade codebase & fix all bugs/exploits first. Because of forum software very big and very hard project. If it will be done by 1-3-5 guys, nothing good will born, will be added extra bugs, and exploits to code (of course because of break focus)

**Comment by sader1992** [comment]
this would be great idea in my opinion , i don't think it need a lot of work , for server management the admins only care about > categories , post views , add new topic , add reply
and fluxcp already have login/register

i was thinking about that today after i installed phpbb , was searching for a way to make shared login between the forum and the official website , but after sometime i deleted phpbb and though i start thinking to make a built in page to add/view posts , and flux have all the other things

good thing google sent me to here xD

**Comment by Akkarinage** [comment]
A 2022 perspective: Fewer people are using forums for their servers, and with recent updates in Discord for threads and forum channels, I no longer see this as being on my to-do list.

If somebody wants to have a go at this they're welcome to, but I'll close this off now.
