### ISSUE TITLE
Highest Peak

### ISSUE THREAD

**Issue by srhmike** [rathena/FluxCP#87]
Maybe I'm missing something but Highest Peak isn't showing on server status.

**Comment by srhmike** [comment]
The player peak kinda shows now.  Itll pop up, but wont show any peak. But then if you refresh the page, Player peak goes away.  And when it does show, it doesnt show any peak, its just blank.
 I also noticed with the sql table online peak, it shows the day, and the highest number it reached that day, so does that mean it only shows the highest peak for the day?

**Comment by srhmike** [comment]
<img width="779" alt="capture" src="https://cloud.githubusercontent.com/assets/23748225/21746824/29f23a36-d510-11e6-847b-454fe4a55eb8.PNG">

**Comment by srhmike** [comment]
<img width="495" alt="capture" src="https://cloud.githubusercontent.com/assets/23748225/21746836/82c9c0c0-d510-11e6-9da2-5a573abe6d48.PNG">

**Comment by daisyanne1380** [comment]
I notice it was not working but then i notice it because something changed in script.c.. when i tried the peakNPC it gave off an sql error.

`[SQL]: DB error - Incorrect table name ''
[Debug]: at c:\users\truenoir\desktop\rathena\rathena-master\src\map\script.c:16
173 - SELECT `users` FROM `` ORDER BY `users` LIMIT 1
[Debug]: Source (NPC): Highest Peak (invisible/not on a map)
[SQL]: DB error - Incorrect table name ''
[Debug]: at c:\users\truenoir\desktop\rathena\rathena-master\src\map\script.c:16
173 - INSERT INTO `` (users, date) VALUES (1, '2017-2-2')
[Debug]: Source (NPC): Highest Peak (invisible/not on a map)
`
