### ISSUE TITLE
Google reCAPTCHA v2

### ISSUE THREAD

**Issue by hurtsky** [rathena/FluxCP#98]
A suggestion in updating current google reCAPTCHA v1 to v2.
small optimization but great feature.
thanks.

**Comment by daisyanne1380** [comment]
while i was browsing to change another section of flux i ran into the code for recaptcha it looks like a lite edit and it would definitely be a great feature.

**Comment by itsmeSryx** [comment]
Added pull request.

https://github.com/rathena/FluxCP/pull/104

Don't forget to get your keys ( https://www.google.com/recaptcha/admin )

**Comment by daisyanne1380** [comment]
hello i downloaded files today and i unpacked it and ran the update but it error so i deleted the entire folder and sql and did a fresh install.  Recaptcha is not working at all now. it uses the  GD2/FreeType2 instead of recaptcha. I also noticed it is ignoring the setting ` 'UseLoginCaptcha'			=> true,` its not displaying any recaptcha at all when logging in. And i do not have any skins and i did clear my websetting. Thanks

**Comment by hurtsky** [comment]
@daisyanne1380 you need to enable
`'EnableReCaptcha'			=> true,`
and add its public key and private key

**Comment by hurtsky** [comment]
@itsmeSryx it working good :+1: just tested it
@Akkarinage

**Comment by daisyanne1380** [comment]
i did a wipe and now it works great thanks
